### ISSUE TITLE
GUI - Aptamer Family Analysis not working

### ISSUE THREAD

**Issue by PJpb** [drivenbyentropy/aptasuite#14]
Hi,
After running the clustering, I get a table of clusters with their IDs and counts on the left of the window.
![image](https://user-images.githubusercontent.com/32843053/36314173-460e88c4-1334-11e8-9465-0e66b5e921ac.png)
I can sort the clusters by size in the table.
![image](https://user-images.githubusercontent.com/32843053/36314220-6d9f9982-1334-11e8-82d2-5789e06136e4.png)

When I press any of the clusters on the left, the app calculates the data for a moment, and next the middle window stays blank but shows some columns. No charts on the right.
![image](https://user-images.githubusercontent.com/32843053/36314254-8ba4db9a-1334-11e8-8ae8-2280758c355e.png)

After I click one of the other clusters on the left, the mid table dissapears and nothing changes on the right.
![image](https://user-images.githubusercontent.com/32843053/36314277-9a7620c0-1334-11e8-98a9-cc4259b0a495.png)

LOG:
[log_2018-02-16_16-26-08.txt](https://github.com/drivenbyentropy/aptasuite/files/1731815/log_2018-02-16_16-26-08.txt)

**Comment by PJpb** [comment]
So after the changes (v0.5.7 now) the bug persists (even when using local instance and files). Here are the source data file and the logs, including the PowerShell console log:
[1302_merged_utf8_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1733890/1302_merged_utf8_1000seq_txt.txt)
[log_2018-02-17_16-46-18.txt](https://github.com/drivenbyentropy/aptasuite/files/1733891/log_2018-02-17_16-46-18.txt)
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1733892/configuration_txt.txt)
[console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1733893/console_log.txt)

**Comment by drivenbyentropy** [comment]
Thanks for the detailed report. I can reproduce this here with any dataset as well and I am looking into it.

**Comment by drivenbyentropy** [comment]
Should be fixed in [v0.5.8](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.5.8).

**Comment by PJpb** [comment]
The bug persists.
Nothing is displayed in the middle window. The middle window (table columns' captions) goes blank after changing the cluster. And actually aptasuite halted totally when I changed the clusters again, I had to force-close it. (App started from PowerShell in Administrator mode)
![image](https://user-images.githubusercontent.com/32843053/36351538-f3564292-14ab-11e8-94cb-efffd94c6481.png)
[1302_merged_utf8_1000seq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1734667/1302_merged_utf8_1000seq_txt.txt)
[console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1734668/console_log.txt)
[log_2018-02-18_12-38-05.txt](https://github.com/drivenbyentropy/aptasuite/files/1734669/log_2018-02-18_12-38-05.txt)
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1734670/configuration_txt.txt)

**Comment by drivenbyentropy** [comment]
This one was hidden deep, but I *think* I fixed it. Please confirm if you have the opportunity. Thanks!

New version is [v0.6.0](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.6.0)

**Comment by PJpb** [comment]
Sorry, no luck. (GUI v0.6.0 started from CLI with administrator's privileges)
![image](https://user-images.githubusercontent.com/32843053/36381591-5f7eb01e-1586-11e8-86d3-76e51f14045a.png)

Also the re-sorting (Div vs Size) doesn't work, it makes the table on the left disappear. Re-running the AptaCluster doesn't make it appear again.
![image](https://user-images.githubusercontent.com/32843053/36381694-b6e697ea-1586-11e8-8b43-5684c86f96c5.png)

[1302_m2k.fastq_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1736969/1302_m2k.fastq_txt.txt)
[console_log.txt](https://github.com/drivenbyentropy/aptasuite/files/1736971/console_log.txt)
[log_2018-02-19_15-04-35.txt](https://github.com/drivenbyentropy/aptasuite/files/1736972/log_2018-02-19_15-04-35.txt)
[configuration_txt.txt](https://github.com/drivenbyentropy/aptasuite/files/1736973/configuration_txt.txt)

**Comment by drivenbyentropy** [comment]
Wow, this is crazy.  

At first I could not reproduce your results for anything. Then I looked again at your console log and and realized that the error was related to parsing a string which was formatted using Javas `DecimalFormat` class to three decimal points.

```java
DecimalFormat df_count = new DecimalFormat("#.###");
```

What I failed to realize before, is that `DecimalFormat` is subject to localization. This means that
```java
double count = 123.456789;
String count_string = df_count.format(count);
System.out.println(count_string);
```
Would print `123.456` in the US, but `123,456` in other countries which use comma as the decimal separator. Hence, any table in AptaSuite showing the sequences would fail to load when creating the cycle counts columns due to  

```java
Number count_number = Double.ParseDouble(count_string);
```

which expects a dot as decimal separator. 

I have now added a fixed locale to all relevant sections in the code. Please let me know if this finally fixes the issue. It should also fix #18. 

New version is [v0.6.1](https://github.com/drivenbyentropy/aptasuite/releases/tag/v0.6.1)

**Comment by PJpb** [comment]
Was this the main error all the time, or have you actually fixed other stuff as well thanks to me being a pain in the ass?;)

It works and it's beautiful. Great job, thank you :)

(More bugs to come over the week when I get down to the juicy stuff and start to analyze real data ;) )

**Comment by drivenbyentropy** [comment]
It was a mixture of smaller issues and this one, the latter being responsible for most of the confusion/non-reproducibility ;-). I am glad it is finally fixed! 

Thanks so much for your persistence.
